# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           "/:categories/:title"

# Setup
title:               Luis Merino
tagline:             'Senior Front-end Developer'
description:         "Hi, I'm Luis Merino. I am a software developer on the multi-browser and multi-platform environment of the web."
url:                 http://www.luismerino.name
baseurl:             /

# About/contact
author:
  name:              Luis Merino
  url:               https://twitter.com/Rendez
  email:             mail@luismerino.name

# Custom vars
version:             1.0.0